[workspace]
resolver = "2"
members = ["day*"]

[workspace.dependencies]
thiserror = "2.0.11"
itertools = "0.14.0"
rayon = "1.8.0"
criterion = { version = "0.5.1", features = ["html_reports"] }
regex = "1.11.1"
num-integer = "0.1.46"
pathfinding = "4.13.1"
